import{S as b,a as p,i as d}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();function L({largeImageURL:t,webformatURL:r,tags:s,likes:n,views:e,comments:o,downloads:i}){return`<li class="gallery-item">
   <a class="gallery-link" href="${t}">
   <img class="gallery-image"
   src="${r}" 
   alt="${s}" />
  </a> <div class="info-box">
  <p>Likes:<span> ${n}</span></p>
        <p>Views:<span> ${e}</span></p>
        <p>Comments:<span> ${o}</span></p>
        <p>Downloads:<span> ${i}</span> </p>    
    </div>
  </li>`}let F=new b(".gallery a",{captionDelay:250,captionsData:"alt",captionPosition:"bottom"});function y(t){const r=t.map(L).join("");a.gallery.insertAdjacentHTML("beforeend",r),F.refresh()}const m=15;async function f(){return p.defaults.baseURL="https://pixabay.com/api/",(await p.get("",{params:{key:"24543353-3824dfbf23e7b5ead533e5f72",image_type:"photo",orientation:"horizontal",safesearch:"true",q:u,page:l,per_page:m}})).data}let u="",l=1;const a={formEl:document.querySelector(".form"),inputEl:document.querySelector(".query"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),btnLoad:document.querySelector(".load-more")},g=a.gallery.querySelector(".gallery-item");a.formEl.addEventListener("submit",q);a.btnLoad.addEventListener("click",w);async function q(t){t.preventDefault(),c();let r=t.target.elements.query.value;if(u=r,r.trim()==="")d.show({message:"Please full the input field",messageColor:"#FFFFFF",backgroundColor:"#B51B1B",position:"topRight"});else try{a.gallery.innerHTML="",a.btnLoad.style.display="none",l=1;const s=await f(l,u);if(s.hits.length>0){if(y(s.hits),a.btnLoad.style.display="block",g){const n=g.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}}else a.gallery.innerHTML="",a.btnLoad.style.display="none",d.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",backgroundColor:"#B51B1B",position:"topRight"});h(s.totalHits,l)}catch(s){console.error("Error data:",s)}c(),t.target.reset()}async function w(){c(),l+=1;const t=await f();y(t.hits),h(t.totalHits,l),c()}function c(){a.loader.classList.toggle("hidden")}function h(t,r){Math.ceil(t/m)===r&&(a.btnLoad.style.display="none",d.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"#FFFFFF",backgroundColor:"#B51B1B",position:"topRight"}))}
//# sourceMappingURL=commonHelpers.js.map
